#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./gl-version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cd gl-release-develop/

bosh -n create release --with-tarball --version "${VERSION}"

mv dev_releases/garden-linux/*.tgz ../bosh-release/garden-linux-${VERSION}.tgz
