#!/bin/bash
# vim: set ft=sh

set -ex

source $(dirname $0)/aufs
cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD

cd src/code.cloudfoundry.org/garden-linux

# Temporary workaround to ensure we can move /sys mounting feature through CI pipeline without 
# depending on it to be present in concourse before being delivered. See #98539374

# the following three lines should be removed after garden-linux has been upgraded in CI 
if ! grep -qs '/sys' /proc/mounts; then
  mount -t sysfs sysfs /sys
fi

permit_device_control
create_loop_devices 256

./scripts/drone-test "$@"
