#!/bin/bash
# vim: set ft=sh

set -ex

cd $(dirname $0)/../..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD

cd src/github.com/cloudfoundry-incubator/garden-linux

./scripts/drone-test "$@"
