#!/bin/bash
# vim: set ft=sh

set -e -x

cd $(dirname $0)/../..

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

cd src/code.cloudfoundry.org/garden-integration-tests
ginkgo -p -nodes=4 performance
