// AUTOGENERATED FILE; see /Users/pivotal/workspace/garden-linux-release/src/github.com/docker/docker/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "f07f542"
	VERSION   string = "1.7.0"

	IAMSTATIC string = "true"
	INITSHA1  string = ""
	INITPATH  string = ""
)
