#!/bin/bash
# vim: set ft=sh

set -e -x

# TODO remove this once garden-linux respects $PATH from docker images
export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

cd $(dirname $0)/../

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

cd src/acceptance-tests
ginkgo -r -p
