#!/bin/bash

set -e

rm -rf src/github.com/docker/docker

git clone --depth 1 --branch v1.9.1 \
  https://github.com/docker/docker src/github.com/docker/docker

pushd src/github.com/docker/docker
  bash ./hack/make/.go-autogen
  rm -rf .git vendor docs man
popd
