#!/bin/sh

set -e

rm -rf src/github.com/docker/docker
git clone https://github.com/docker/docker src/github.com/docker/docker
pushd src/github.com/docker/docker
git checkout v1.8.3
./hack/make/.go-autogen
rm -rf .git
popd
