#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cd release-develop/

bosh -n create release --with-tarball --version "${VERSION}"

mv dev_releases/garden-linux/*.tgz ../garden-linux-${VERSION}.tgz
