#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cd release-develop/

export GOPATH=$PWD
pushd src/github.com/docker/docker
./hack/make.sh || true
popd
unset GOPATH

bosh -n create release --with-tarball --version "${VERSION}"

mv dev_releases/garden-linux/*.tgz ../garden-linux-${VERSION}.tgz
