#!/bin/bash
# vim: set ft=sh

set -e -x

cd $(dirname $0)/../

export GOPATH=$PWD:$PWD/src/garden-integration-tests/Godeps/_workspace
export PATH=$GOPATH/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

cd src/garden-integration-tests
ginkgo -p -nodes=4
