#!/bin/bash
# vim: set ft=sh

set -ex

cd $(dirname $0)/..

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD

pushd src/github.com/docker/docker
./hack/make.sh || true
popd

cd src/github.com/cloudfoundry-incubator/garden-linux

./scripts/drone-test "$@"
