#!/bin/bash
set -e -x

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)
cd $ROOT_DIR_PATH

pushd src/code.cloudfoundry.org/garden-linux
	ginkgo -r
popd

pushd src/code.cloudfoundry.org/garden-shed
	ginkgo -r
popd

pushd src/code.cloudfoundry.org/garden
	ginkgo -r
popd

./scripts/remote-fly ci/nested-garden-linux-tests.yml
./scripts/remote-fly ci/nested-shed-tests.yml
./scripts/remote-fly ci/nested-tests.yml
